/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function setWindowWorker(hWnd: number): void
export function restoreWindowWorker(): void
export function showDesktopIcon(): void
export function hideDesktopIcon(): void
export const enum UserState {
  QunsNotPresent = 1,
  QunsBusy = 2,
  QunsRunningD3dFullScreen = 3,
  QunsPresentationMode = 4,
  QunsAcceptsNotifications = 5,
  QunsQuietTime = 6,
  QunsApp = 7
}
