/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function setWindowWorker(hWnd: number): void
export function restoreWindowWorker(): void
export function showDesktopIcon(): void
export function hideDesktopIcon(): void
export function showShellWindow(): void
export function hideShellWindow(): void
export function showPeekWindow(): void
export function hidePeekWindow(): void
export function queryUserState(): number
export function setTaskbarStyle(accept: ACCENT, color: number): boolean
export function restoreTaskbarStyle(): boolean
export const enum UserState {
  QunsNotPresent = 1,
  QunsBusy = 2,
  QunsRunningD3dFullScreen = 3,
  QunsPresentationMode = 4,
  QunsAcceptsNotifications = 5,
  QunsQuietTime = 6,
  QunsApp = 7
}
export const enum ACCENT {
  AccentEnableGradient = 1,
  AccentEnableTransparentgradient = 2,
  AccentEnableBlurbehind = 3,
  AccentEnableFluent = 4,
  AccentNormal = 150
}
